version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./
      dockerfile: src/dockerfile
    container_name: e-commerce-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://frontend:3000
    volumes:
      - ./src/uploads:/usr/src/app/src/uploads
      - backend_node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  # Frontend React service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: e-commerce-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL_DOCKER=http://backend:3001
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules:
