version: '3.8'

services:
  # Redis for session management and caching
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Backend API service (for api.jabick.site)
  backend:
    build:
      context: ./
      dockerfile: src/dockerfile
      args:
        - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./src/uploads:/usr/src/app/src/uploads
    ports:
      - "3001:3001"  # Expose directly for api.jabick.site
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    labels:
      - "com.docker.compose.service=backend"

  # Frontend React service (for jabick.site)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - VITE_BACKEND_API_URL=https://api.jabick.site
    ports:
      - "3000:3000"  # Expose directly for jabick.site
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
