FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json from root folder
COPY package*.json ./
RUN npm install

# Bundle app source
COPY src/ ./src/
COPY .env ./

# Expose the port the app runs on
EXPOSE 3001

# Command to run the application
CMD ["npm", "start"]
