name: deploy 2

on:
  push:
    branches:
      - deploy_2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github_action_ci_key
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/Projects/E-commerce-Computers-Selling
            git pull origin deploy_2
            docker-compose pull
            docker-compose up -d --build
          EOF
